### ISSUE TITLE
Test if line of sight offset is broken when crouching

### ISSUE THREAD

**Issue by SkyeErnst** [SkyeErnst/StealthGame#6]
A hard-coded offset to the raycast position could cause the raycast to miss while the player is crouching. Some testing is needed to determine if this is the case.

If so, recommend one of two courses of action:

- place an empty game object within the hierarchy of the player and use the transform of that object as the target of the raycast
- Use the camera transform instead, though it should be double checked to make sure the camera transform is within the collider

**Comment by Vargrak** [comment]
Height of the raycast is consistent when crouched.
